GET http://localhost:8080/user

###

GET http://localhost:8080/user?status=foo

###

GET http://localhost:8080/user?status=available

###

GET http://localhost:8080/user?status=blocked

###

GET http://localhost:8080/user/6faf60f3-3cd7-4a3a-b5c6-59738b8f725e

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "name" : "John Doe",
  "status": "available",
  "address": {
    "street": "Doe Street",
    "city": "Doe-Town",
    "state": "Doe-County",
    "zip": "10234"
  }
}

###

PUT http://localhost:8080/user/6faf60f3-3cd7-4a3a-b5c6-59738b8f725e
Content-Type: application/json

{
  "name" : "John Doe2",
  "status": "blocked",
  "address": {
    "street": "Doe Street",
    "city": "Doe-Town",
    "state": "Doe-County",
    "zip": "10234"
  },
  "fallbackAddresses": [
    {
      "street": "Doe Street2",
      "city": "Doe-Town2",
      "state": "Doe-County2",
      "zip": "10234"
    },
    {
      "street": "Doe Street3",
      "city": "Doe-Town3",
      "state": "Doe-County3",
      "zip": "10234"
    }
  ]
}

###

DELETE http://localhost:8080/user/6faf60f3-3cd7-4a3a-b5c6-59738b8f725e