package com.ancientlightstudios.quarkus.kotlin.openapi.handler.json

import com.ancientlightstudios.quarkus.kotlin.openapi.emitter.ModelDeserializationFeature

object JsonDeserializationFeature : ModelDeserializationFeature