package com.ancientlightstudios.quarkus.kotlin.openapi.inspection

import com.ancientlightstudios.quarkus.kotlin.openapi.models.transformable.TransformableHeaderParameter

class ResponseHeaderInspection(val header: TransformableHeaderParameter)