openapi: 3.1.0
info:
  title: Filestore
  version: 1.0.0
tags:
  - name: plain
  - name: json

paths:
  /features/plain/optional/enum:
    post:
      tags:
        - plain
      operationId: plainOptionalEnum
      requestBody:
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/SimpleEnumOptional'
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SimpleEnumOptional'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/plain/required/enum:
    post:
      tags:
        - plain
      operationId: plainRequiredEnum
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/SimpleEnum'
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SimpleEnum'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/optional/object:
    post:
      tags:
        - json
      operationId: jsonOptionalObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleObjectOptional'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleObjectOptional'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/required/object:
    post:
      tags:
        - json
      operationId: jsonRequiredObject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleObject'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/form/required/object:
    post:
      tags:
        - form
      operationId: formRequiredObject
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SimpleForm'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleForm'
        '400':
          $ref: '#/components/responses/OperationError400'

components:

  schemas:
    SimpleEnum:
      type: string
      enum:
        - first
        - second

    SimpleEnumOptional:
      $ref: '#/components/schemas/SimpleEnum'
      type:
        - 'null'

    SimpleObject:
      type: object
      properties:
        nameOptional:
          type: string
          default: 'i am optional'
        nameRequired:
          type: string
          default: 'i am required'
        statusOptional:
          $ref: '#/components/schemas/SimpleEnum'
        statusRequired:
          $ref: '#/components/schemas/SimpleEnum'
        itemsOptional:
          type: array
          items:
            type: string
        itemsRequired:
          type: array
          items:
            type: string
      required:
        - nameRequired
        - statusRequired
        - itemsRequired

    SimpleObjectOptional:
      $ref: '#/components/schemas/SimpleObject'
      type:
        - 'null'

    SimpleForm:
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/SimpleEnum'
      required:
        - name
        - status

    OperationError:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
      required:
        - messages

  responses:
    OperationError400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'
