openapi: 3.1.0
info:
  title: Test-Suit
  version: 1.0.0
  description: fragment of the overall test suit

paths:
  /features/form/object:
    post:
      tags:
        - form
      operationId: formObject
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SimpleForm'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleForm'
        '400':
          $ref: '#/components/responses/OperationError400'

components:

  schemas:
    FormEnum:
      type: string
      enum:
        - first
        - second

    SimpleForm:
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/FormEnum'
      required:
        - name
        - status

    OperationError:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
      required:
        - messages

  responses:
    OperationError400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'
