openapi: 3.1.0
info:
  title: Test-Suit
  version: 1.0.0
  description: fragment of the overall test suit

paths:
  /features/json/optional/object:
    post:
      tags:
        - json
      operationId: jsonOptionalObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleObjectOptional'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleObjectOptional'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/required/object:
    post:
      tags:
        - json
      operationId: jsonRequiredObject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleObject'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/optional/array:
    post:
      tags:
        - json
      operationId: jsonOptionalArray
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SimpleObjectOptional'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type:
                  - array
                  - "null"
                items:
                  $ref: '#/components/schemas/SimpleObjectOptional'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/required/array:
    post:
      tags:
        - json
      operationId: jsonRequiredArray
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/SimpleObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SimpleObject'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/optional/map:
    post:
      tags:
        - json
      operationId: jsonOptionalMap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SimpleObjectOptional'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type:
                  - object
                  - "null"
                additionalProperties:
                  $ref: '#/components/schemas/SimpleObjectOptional'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/required/map:
    post:
      tags:
        - json
      operationId: jsonRequiredMap
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/SimpleObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/SimpleObject'
        '400':
          $ref: '#/components/responses/OperationError400'

  /features/json/nestedMap:
    post:
      tags:
        - json
      operationId: jsonNestedMap
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Container'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        '400':
          $ref: '#/components/responses/OperationError400'

components:
  schemas:
    JsonEnum:
      type: string
      enum:
        - first
        - second
      x-enum-item-names:
        first: TheFirst

    SimpleObject:
      type: object
      properties:
        nameOptional:
          description: "this allOf should be stripped out by a refactoring"
          allOf:
            - type: string
              default: 'i am optional'
        nameRequired:
          type: string
          default: 'i am required'
        statusOptional:
          $ref: '#/components/schemas/JsonEnum'
        statusRequired:
          $ref: '#/components/schemas/JsonEnum'
        itemsOptional:
          type: array
          items:
            type: number
            format: int32
        itemsRequired:
          type: array
          items:
            type: number
            format: int32
      required:
        - nameRequired
        - statusRequired
        - itemsRequired

    Container:
      type: object
      properties:
        withNonNullValues:
          $ref: '#/components/schemas/ContainerPart'
          x-model-name: NonNullContainerPart
          additionalProperties:
            type: number
            format: int32
            maximum: 100
        withNullableValues:
          $ref: '#/components/schemas/ContainerPart'
          x-model-name: NullableContainerPart
          additionalProperties:
            type:
              - number
              - 'null'
            format: int32
            maximum: 100
      required:
        - withNonNullValues
        - withNullableValues

    ContainerPart:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: number
          format: int64
      required:
        - foo

    SimpleObjectOptional:
      $ref: '#/components/schemas/SimpleObject'
      type:
        - 'null'

    OperationError:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
      required:
        - messages

  responses:
    OperationError400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'
