openapi: 3.1.0
servers:
  - url: /v3
info:
  description: our test interface
  version: 1.0.17
  title: Test Interface
paths:
  /rating/{movieId}:
    parameters:
      - $ref: "#/components/parameters/MovieId"

    get:
      operationId: getMovieRating
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieRating"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputError"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationError"


    post:
      operationId: addMovieRating
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Rating"
      responses:
        '204':
          description: Successful operation
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputError"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationError"

  /rating/{movieId}/{ratingId}:
    delete:
      operationId: deleteMovieRating
      parameters:
        - $ref: "#/components/parameters/MovieId"
        - name: ratingId
          in: path
          description: ratingId
          required: true
          schema:
            $ref: "#/components/schemas/Id"
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputError"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationError"
