openapi: 3.1.0
info:
  title: Filestore
  version: 1.0.0
paths:
  /files:
    post:
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileUploadRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadResponse'
        '400':
          $ref: '#/components/responses/OperationError400'
        '500':
          $ref: '#/components/responses/OperationError500'

  /files/{id}:
    parameters:
      - $ref: '#/components/parameters/FileId'

    get:
      operationId: downloadFile
      responses:
        '200':
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/OperationError400'
        '404':
          $ref: '#/components/responses/OperationError404'
        '500':
          $ref: '#/components/responses/OperationError500'

    delete:
      operationId: deleteFile
      responses:
        '204':
          description: No content
        '400':
          $ref: '#/components/responses/OperationError400'
        '500':
          $ref: '#/components/responses/OperationError500'

    post:
      operationId: changeExpireDate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpireDateChangeRequest'
      responses:
        '204':
          description: No content
        '400':
          $ref: '#/components/responses/OperationError400'
        '404':
          $ref: '#/components/responses/OperationError404'
        '500':
          $ref: '#/components/responses/OperationError500'

  /revoke:
    post:
      operationId: revokeToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRevokeRequest'
      responses:
        '200':
          description: Ok
        '400':
          $ref: '#/components/responses/OperationError400'

components:

  schemas:
    Id:
      type: string
      format: uuid

    Instant:
      type: string
      format: instant

    FileUploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
        expireDate:
          $ref: '#/components/schemas/Instant'
      required:
        - file
        - expireDate

    FileUploadResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
      required:
        - id

    ExpireDateChangeRequest:
      type: object
      properties:
        expireDate:
          $ref: '#/components/schemas/Instant'
      required:
        - expireDate

    TokenRevokeRequest:
      type: object
      properties:
        token:
          type: string
      required:
        - token

    OperationError:
      type: object
      properties:
        message:
          type: string
      required:
        - message

  parameters:
    FileId:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'

  responses:
    OperationError400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'

    OperationError404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'

    OperationError500:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationError'
