package com.ancientlightstudios.quarkus.kotlin.openapi.handler.plain

import com.ancientlightstudios.quarkus.kotlin.openapi.emitter.ModelSerializationFeature

object PlainSerializationFeature : ModelSerializationFeature